-- MySQL Script generated by MySQL Workbench
-- Sat Nov  15 01:00:25 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema flights_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema flights_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `flights_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `flights_db` ;

-- -----------------------------------------------------
-- Table `flights_db`.`airline`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flights_db`.`airline` (
  `AIRLINE_ID` SMALLINT NOT NULL,
  `UNIQUE_CARRIER` VARCHAR(50) NOT NULL,
  `UNIQUE_CARRIER_NAME` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`AIRLINE_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `flights_db`.`aircraft`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flights_db`.`aircraft` (
  `AIRCRAFT_ID` SMALLINT NOT NULL,
  `TAIL_NUM` VARCHAR(50) NOT NULL,
  `OP_CARRIER_FL_NUM` VARCHAR(50) NOT NULL,
  `UNIQUE_CARRIER` VARCHAR(50) NOT NULL,
  `AIRLINE_ID` SMALLINT NOT NULL,
  PRIMARY KEY (`AIRCRAFT_ID`),
  INDEX `fk_aircraft_airline_idx` (`AIRLINE_ID` ASC),
  CONSTRAINT `fk_aircraft_airline`
    FOREIGN KEY (`AIRLINE_ID`)
    REFERENCES `flights_db`.`airline` (`AIRLINE_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `flights_db`.`location`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flights_db`.`location` (
  `LOCATION_ID` SMALLINT NOT NULL,
  `CITY` VARCHAR(30) NOT NULL,
  `STATE` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`LOCATION_ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `flights_db`.`airport`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flights_db`.`airport` (
  `AIRPORT_ID` SMALLINT NOT NULL,
  `AIRPORT_NAME` VARCHAR(255) NOT NULL,
  `LATITUDE` FLOAT NOT NULL,
  `LONGITUDE` FLOAT NOT NULL,
  `LOCATION_ID` SMALLINT NOT NULL,
  PRIMARY KEY (`AIRPORT_ID`, `LOCATION_ID`),
  INDEX `fk_airport_location1_idx` (`LOCATION_ID` ASC),
  CONSTRAINT `fk_airport_location1`
    FOREIGN KEY (`LOCATION_ID`)
    REFERENCES `flights_db`.`location` (`LOCATION_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `flights_db`.`flight`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flights_db`.`flight` (
  `ID` VARCHAR(50) NOT NULL,
  `CRS_DEP_TIME` TIME NULL DEFAULT NULL,
  `DEP_TIME` TIME NULL DEFAULT NULL,
  `CRS_ARR_TIME` TIME NULL DEFAULT NULL,
  `ARR_TIME` TIME NULL DEFAULT NULL,
  `CANCELLED` SMALLINT ZEROFILL NULL DEFAULT NULL,
  `DISTANCE` SMALLINT NULL DEFAULT NULL,
  `CARRIER_DELAY` SMALLINT NULL DEFAULT NULL,
  `WEATHER_DELAY` SMALLINT NULL DEFAULT NULL,
  `NAS_DELAY` SMALLINT NULL DEFAULT NULL,
  `SECURITY_DELAY` SMALLINT NULL DEFAULT NULL,
  `DATE` DATE NOT NULL,
  `ORIGIN_AIRPORT_ID` SMALLINT NOT NULL,
  `DEST_AIRPORT_ID` SMALLINT NOT NULL,
  `AIRCRAFT_ID` SMALLINT NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_flight_airport1_idx` (`ORIGIN_AIRPORT_ID` ASC),
  INDEX `fk_flight_airport2_idx` (`DEST_AIRPORT_ID` ASC),
  INDEX `fk_flight_aircraft1_idx` (`AIRCRAFT_ID` ASC),
  CONSTRAINT `fk_flight_airport1`
    FOREIGN KEY (`ORIGIN_AIRPORT_ID`)
    REFERENCES `flights_db`.`airport` (`AIRPORT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flight_airport2`
    FOREIGN KEY (`DEST_AIRPORT_ID`)
    REFERENCES `flights_db`.`airport` (`AIRPORT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_flight_aircraft1`
    FOREIGN KEY (`AIRCRAFT_ID`)
    REFERENCES `flights_db`.`aircraft` (`AIRCRAFT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `flights_db`.`weather`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `flights_db`.`weather` (
  `WEATHER_ID` SMALLINT NOT NULL,
  `STATION` VARCHAR(30) NOT NULL,
  `DATE` DATE NOT NULL,
  `AWND` FLOAT NULL DEFAULT NULL,
  `PGTM` FLOAT NULL DEFAULT NULL,
  `PRCP` FLOAT NULL DEFAULT NULL,
  `TSUN` VARCHAR(30) NULL DEFAULT NULL,
  `SNOW` SMALLINT NULL DEFAULT NULL,
  `SNWD` SMALLINT NULL DEFAULT NULL,
  `TAVG` SMALLINT NULL DEFAULT NULL,
  `TMAX` SMALLINT NULL DEFAULT NULL,
  `TMIN` SMALLINT NULL DEFAULT NULL,
  `WT01` TINYINT(1) NULL DEFAULT NULL,
  `WT02` TINYINT(1) NULL DEFAULT NULL,
  `WT03` TINYINT(1) NULL DEFAULT NULL,
  `WT04` TINYINT(1) NULL DEFAULT NULL,
  `WT05` TINYINT(1) NULL DEFAULT NULL,
  `WT06` TINYINT(1) NULL DEFAULT NULL,
  `WT07` TINYINT(1) NULL DEFAULT NULL,
  `WT08` TINYINT(1) NULL DEFAULT NULL,
  `WT09` TINYINT(1) NULL DEFAULT NULL,
  `WT10` TINYINT(1) NULL DEFAULT NULL,
  `AIRPORT_ID` SMALLINT NOT NULL,
  PRIMARY KEY (`WEATHER_ID`, `AIRPORT_ID`),
  INDEX `fk_weather_airport1_idx` (`AIRPORT_ID` ASC),
  CONSTRAINT `fk_weather_airport1`
    FOREIGN KEY (`AIRPORT_ID`)
    REFERENCES `flights_db`.`airport` (`AIRPORT_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
